on:
  push:
    branches:
      - deploy-page

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      - uses: actions/setup-node@v1
        with:
          node-version: v20.11.1
      - name: install packages
        run: |
          npm i -g pnpm@9.0.2
          cd docs
          pnpm i
      - name: build
        run: |
          cd docs
          pnpm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: docs/.vitepress/dist
          destination_dir: notes
          publish_branch: main
          external_repository: micaiguai/micaiguai.github.io
