on:
  push:
    branches:
      - deploy-page

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for WeChat Work
        uses: chf007/action-wechat-work@1.0.8
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: text
          content: notes start
      - uses: actions/checkout@v2
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      - uses: actions/setup-node@v1
        with:
          node-version: v20.11.1
      - name: install packages
        run: |
          npm i -g pnpm@9.0.2
          cd docs
          pnpm i
      - name: build
        run: |
          pnpm run build
      # - name: artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: dist
          destination_dir: notes
          publish_branch: main
          external_repository: micaiguai/micaiguai.github.io
      - name: GitHub Action for WeChat Work
        if: always()
        uses: chf007/action-wechat-work@1.0.8
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: text
          content: 'notes ${{job.status}}'
